name: Build Sitemap

on:
  schedule:
    # Run on the 1st day of every month at 2:00 AM UTC
    - cron: "0 2 1 * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up permissions
        run: |
          chmod +x ./build-sitemap.sh

      - name: Run sitemap build script
        run: |
          ./build-sitemap.sh

      - name: Check if sitemap files were generated
        run: |
          if [ ! -d "sitemap" ]; then
            echo "Error: sitemap directory was not created"
            exit 1
          fi

          if [ ! -f "sitemap/index.xml" ]; then
            echo "Error: index.xml was not generated"
            exit 1
          fi

          echo "Sitemap files generated successfully:"
          ls -la sitemap/

      - name: Upload build log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-sitemap-log
          path: build-sitemap.log
          retention-days: 5

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are any changes to commit
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git add sitemap/
            git add build-sitemap.log
            git commit -m "Update sitemap files - $(date '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
